const printingModule = @import("modules/01_printing.zig");
const stringsModule = @import("modules/02_strings.zig");
const undefinedModule = @import("modules/03_undefined.zig");
const testingModule = @import("modules/04_testing.zig");
const numbersModule = @import("modules/05_numbers.zig");
const arraysModule = @import("modules/06_arrays.zig");
const vectorsModule = @import("modules/07_vectors.zig");
const pointersModule = @import("modules/08_pointers.zig");
const alignmentModule = @import("modules/09_alignment.zig");
const structsModule = @import("modules/10_structs.zig");
const structsExtModule = @import("modules/11_structs_ext.zig");
const structsAnonymousModule = @import("modules/12_structs_anonymous.zig");
const enumsModule = @import("modules/13_enums.zig");
const unionsModule = @import("modules/14_unions.zig");
const switchModule = @import("modules/15_switch.zig");
const whileModule = @import("modules/16_while.zig");
const forModule = @import("modules/17_for.zig");
const deferModule = @import("modules/18_defer.zig");
const functionsModule = @import("modules/19_functions.zig");
const errorsModule = @import("modules/20_errors.zig");
const optionalsModule = @import("modules/21_optionals.zig");
const castingModule = @import("modules/22_casting.zig");
const comptimeModule = @import("modules/23_comptime.zig");
const allocatorsModule = @import("modules/24_allocators.zig");

pub fn main() void {
    printingModule.printTopic();
    stringsModule.printTopic();
    undefinedModule.printTopic();
    testingModule.printTopic();
    numbersModule.printTopic();
    arraysModule.printTopic();
    vectorsModule.printTopic();
    pointersModule.printTopic();
    alignmentModule.printTopic();
    structsModule.printTopic();
    structsExtModule.printTopic();
    structsAnonymousModule.printTopic();
    enumsModule.printTopic();
    unionsModule.printTopic();
    switchModule.printTopic();
    whileModule.printTopic();
    forModule.printTopic();
    deferModule.printTopic();
    functionsModule.printTopic();
    errorsModule.printTopic();
    optionalsModule.printTopic();
    castingModule.printTopic();
    comptimeModule.printTopic();
    allocatorsModule.printTopic();
}
