const printingModule = @import("modules/1_printing.zig");
const stringsModule = @import("modules/2_strings.zig");
const undefinedModule = @import("modules/3_undefined.zig");
const testingModule = @import("modules/4_testing.zig");
const numbersModule = @import("modules/5_numbers.zig");
const arraysModule = @import("modules/6_arrays.zig");
const vectorsModule = @import("modules/7_vectors.zig");
const pointersModule = @import("modules/8_pointers.zig");
const alignmentModule = @import("modules/9_alignment.zig");
const structsModule = @import("modules/10_structs.zig");
const structsExtModule = @import("modules/11_structs_ext.zig");
const structsAnonymousModule = @import("modules/12_structs_anonymous.zig");
const enumsModule = @import("modules/13_enums.zig");
const unionsModule = @import("modules/14_unions.zig");
const switchModule = @import("modules/15_switch.zig");
const whileModule = @import("modules/16_while.zig");
const forModule = @import("modules/17_for.zig");
const deferModule = @import("modules/18_defer.zig");
const functionsModule = @import("modules/19_functions.zig");
const errorsModule = @import("modules/20_errors.zig");

pub fn main() void {
    printingModule.printTopic();
    stringsModule.printTopic();
    undefinedModule.printTopic();
    testingModule.printTopic();
    numbersModule.printTopic();
    arraysModule.printTopic();
    vectorsModule.printTopic();
    pointersModule.printTopic();
    alignmentModule.printTopic();
    structsModule.printTopic();
    structsExtModule.printTopic();
    structsAnonymousModule.printTopic();
    enumsModule.printTopic();
    unionsModule.printTopic();
    switchModule.printTopic();
    whileModule.printTopic();
    forModule.printTopic();
    deferModule.printTopic();
    functionsModule.printTopic();
    errorsModule.printTopic();
}
